controllers:
    resource: ../src/Controller/
    type: attribute

# accueil:
#     path: /
#     controller: App\Controller\MainController::accueil
afficher:
    path: afficher
    controller: App\Controller\AgencesController::agences_afficher
